# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    
    encoders:
        Site\FrontEndBundle\Entity\Users:
            algorithm: sha512
            encode-as-base64: false
            iterations: 10


    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory: ~
        main:
            entity: { class: SiteFrontEndBundle:Users, property: username }

        
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        main:
            pattern: ^/.*
            form_login:
                
                login_path: _security_login
                check_path: _security_check
                default_target_path: /
            logout:
                path: _security_logout
                target: /
            security: true
            anonymous: true
            
    access_control:
        - { path: /admin/.*, role: ROLE_USER }
        - { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }


    
       
