Site\FrontEndBundle\Entity\Categories:
    type: entity
    table: null
    repositoryClass: Site\FrontEndBundle\Repository\CategoriesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        created:
            type: datetime
        slug:
            type: string
            length: 255
    oneToMany:
        post:
            targetEntity: Post
            mappedBy: categories
    lifecycleCallbacks: {  }
