Site\FrontEndBundle\Entity\Users:
    type: entity
    table: users
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
        password:
            type: string
            length: 255
            
        salt:
            type: string
            length: 255
            
        surname:
            type: string
            length: 255
        name:
            type: string
            length: 255
        created:
            type: datetime
    
    manyToMany:
        roles:
            targetEntity: Roles
            inversedBy: users
            joinTable:
                name: roles_users
                joinColumns:
                    users_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    roles_id:
                        referencedColumnName: id
    lifecycleCallbacks: {  }
