Site\FrontEndBundle\Entity\Users:
    type: entity
    table: users
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
