_security_login:
    pattern:  /login
    defaults: { _controller: SiteFrontEndBundle:Security:login }

_security_check:
    pattern:  /login_check

_security_logout:
    pattern:  /logout

admin_home:
    pattern:  /admin/dashboard/
 #   defaults: { _controller: SiteFrontEndBundle:Admin:index }

site_front_end_homepage:
    path:     /page/{page}
    defaults: { _controller: SiteFrontEndBundle:Posts:index , page : 1 }
    requirements:
        page: \d+

post:
    path:     /post/{slug}
    defaults: { _controller: SiteFrontEndBundle:Posts:showPostBySlug }

posts_by_tag:
    path:     /tag/{slug}
    defaults: { _controller: SiteFrontEndBundle:Posts:showPostsByTag }
    
posts_by_category:
    path:     /category/{slug}/{page}
    defaults: { _controller: SiteFrontEndBundle:Posts:showPostsByCategory, page: 1 }
    requirements:
        page: \d+

form:
    path:     /form
    defaults: { _controller: SiteFrontEndBundle:Form:getTagsAndCategories }
    
get_form:
    path:     /get_form
    defaults: { _controller: SiteFrontEndBundle:Form:getForm }
    
