<?php

namespace Site\FrontEndBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function count()
    {
        $qb = $this->createQueryBuilder('p');
        $qb->select('COUNT(p.id)');
        return $qb->getQuery()->getSingleScalarResult();
    }
    
    public function getNumberOfPosts($slug = '')
    {
        $qb = $this->createQueryBuilder('p');
        $qb->andWhere('c.slug:slug');
        if ($slug != null) {
        $qb->join('SiteFrontEndBundle:Categories','c')
           ->setParameter('slug', $slug);
        }
        $qb->orderBy('p.id', 'DESC')
           ->setMaxResults(3);
        return $qb->getQuery()->getResult();
    }
    
//    public function findByAuthor($uname)
//    {
//        $qb=$this->createQueryBuilder('u');
//        $qb->andWhere('u.username=:uname')
//           ->join('Bundle:Users','u')
//           ->setParameter('uname',$uname);
//    }
}
